config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users
  root 'instruments#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
  <div class="notification is-info global-notification" id="mb-0">
    <button class="delete"></button>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification" id="mb-0">
    <button class="delete"></button>
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "eCommerce app", root_path, class: "navbar-item is-size-5 b" %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

<div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to "Item 1", "#", class: "navbar-item"  %>


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Cart and items
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Cart index", carts_path, class: "navbar-item" %>
          <%= link_to "Line items index", line_items_path, class: "navbar-item" %>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">

    <% if cart_has_items %>
      <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
      <span class="icon is-small">
        <i class="fa fa-shopping-cart"></i>
      </span>
      <span>Cart
        <%= cart_count_over_one %>
        </span>
      <% end %>
    <% end %>

      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to new_instrument_path, class: "button is-dark" do %>
              <i class="fa fa-sell"> Sell </i>  
            <% end %>
            <%= link_to edit_user_registration_path(current_user) , class: "button is-warning" do %>
              <i class="fa fa-edit"> <%= current_user.username %>'s profile</i>  
            <% end %>
            <%= link_to destroy_user_session_path , method: :delete, class: "button is-warning" do %>
              <i class="fa fa-user"> Log out</i>  
            <% end %>
          <% else %>
            <%= link_to new_user_session_path , class: "button is-warning" do %>
              <i class="fa fa-user"> Log in</i>  
            <% end %>
            <%= link_to new_user_registration_path , class: "button is-warning" do %>
              <i class="fa fa-user-plus"> Sign Up</i>  
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_validations.html.erb
<% if obj.errors.any? %>
  <div class="notification is-warning">
    <button class="delete"></button>
    <h2 class=" title is-5 pt2"><%= pluralize(obj.errors.count, "error") %> prohibited this record from being saved:</h2>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndyDiscussions</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <%= render 'layouts/messages'%>
    <%= render 'layouts/navbar' %>
    <%= yield(:header) %>
    <div class="container pa3">
      <%= yield %>
      <hr>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>